services:
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8001:8001"
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8002:8002"
    restart: unless-stopped
