services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    env_file:
      - ./auth-service/.env.development
    volumes:
      - ./logs/dev:/logs
    environment:
      - GIN_MODE=debug
      - APP_ENV=development

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    env_file:
      - ./user-service/.env.development
    volumes:
      - ./logs/dev:/logs
    environment:
      - GIN_MODE=debug
      - APP_ENV=development

  quiz-service:
    build:
      context: .
      dockerfile: quiz-service/Dockerfile
    env_file:
      - ./quiz-service/.env.development
    volumes:
      - ./logs/dev:/logs
    environment:
      - GIN_MODE=debug
      - APP_ENV=development

  email-service:
    build:
      context: .
      dockerfile: email-service/Dockerfile
    env_file:
      - ./email-service/.env.development
    volumes:
      - ./logs/dev:/logs
    environment:
      - GIN_MODE=debug
      - APP_ENV=development