events {}

http {

    upstream auth_service {
        server auth-service:8001;
    }

    upstream user_service {
        server user-service:8002;
    }

    upstream email_service {
        server email-service:8082;
    }

    upstream department_service {
        server department-service:8003;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth_service/;
        }

        location /users/ {
            proxy_pass http://user_service/;
        }

        location /emails/ {
            proxy_pass http://email_service/;
        }

        location /department/ {
            proxy_pass http://department_service/;
        }
    }
}